# -*- coding: utf-8 -*-
"""Maximl_code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iiIOz_J3vZINTS0jmRsX8ipZbnjhG8R3
"""

a=input("enter the string  ")
b=[]
n=len(a)
for i in range(0,n):
  for j in range(i+1,n+1):
    l=a[i:j]
    b.append(l)
c=[]
for i in b:
  d=set(i)
  c.append(len(d))
print(max(c))

